### DISCUSSION TITLE
CSS transitions breaks on component rerender

### DISCUSSION THREAD

**Discussion by marcuslindblom** [lit/lit#2801] [Q&A]
I have list of thumbnail components with built in progress bar for upload. At the end of the upload I have a css transition to reveal the uploaded image. I enable the transition with two simple css classes like this.

```css
    .thumbnail--processing {
      transition: clip-path 800ms cubic-bezier(0.33, 0, 0, 1) 0ms,
        opacity 800ms cubic-bezier(0.17, 0.17, 0, 1) 0ms,
        transform 800ms cubic-bezier(0.17, 0.17, 0, 1) 0ms;
      opacity: 0;
      position: absolute;
      clip-path: circle(0 at center);
      transform: scale(0.95);
    }
    .thumbnail--loaded {
      clip-path: circle(240px at center);
      transform: scale(1);
      opacity: 1;
      position: relative;
    }
```

The embedded video shows the problem when the first files are uploaded to 100% you can see the janky transition/animation. Can anyone point me in the right direction on how to solve this?

https://user-images.githubusercontent.com/319720/165782501-7919c62a-07f8-4509-9cb7-73af6a8f2b92.mov

.
