### DISCUSSION TITLE
How to re-use css styles ?

### DISCUSSION THREAD

**Discussion by 0xbuidler** [lit/lit#4633] [General]
I have to style a div that will have different variants. I don't want to re-write the base multiple times. It seems that I failed to see how we could do that in the doc.

I wanted to do something like that:
```css
const baseStyle = css`
	display: flex;
	gap: 8px;
	border-radius: 100px;
	background-color: hsla(0, 0%, 4%, 1);
	color: hsla(0, 0%, 98%, 1);
`;

export const style = css`
	.layer1 {
		${baseStyle};

		// More style
	}
`;
```
